using System.ComponentModel;

namespace IpMonitor;

partial class SettingsForm
{
    private IContainer? components = null;
    private Label lblHeader;
    private Label lblHeaderHint;
    private TabControl tabSettings;
    private TabPage tabGeneral;
    private TabPage tabMonitoring;
    private TabPage tabNotifications;
    private TabPage tabJournal;
    private TabPage tabBackups;
    private CheckBox chkStartMonitoring;
    private CheckBox chkMinimizeToTray;
    private CheckBox chkStartWithWindows;
    private CheckBox chkAlwaysOnTop;
    private Label lblGeneralHint;
    private Label lblInterval;
    private NumericUpDown nudInterval;
    private Label lblSeconds;
    private Label lblTimeout;
    private NumericUpDown nudTimeout;
    private Label lblMilliseconds;
    private Label lblFailures;
    private NumericUpDown nudFailures;
    private Label lblFailuresHint;
    private Label lblSuccesses;
    private NumericUpDown nudSuccesses;
    private Label lblSuccessesHint;
    private CheckBox chkLatencyWarning;
    private Label lblLatencyThreshold;
    private NumericUpDown nudLatencyThreshold;
    private Label lblLatencyMs;
    private Label lblLatencyChecks;
    private NumericUpDown nudLatencyChecks;
    private Label lblLatencyChecksUnit;
    private Label lblLatencyHint;
    private CheckBox chkSoundOffline;
    private CheckBox chkSoundOnline;
    private CheckBox chkTrayNotifications;
    private Button btnTestOfflineSound;
    private Button btnTestOnlineSound;
    private Label lblRetention;
    private NumericUpDown nudRetention;
    private Label lblDays;
    private CheckBox chkAutoDelete;
    private Button btnOpenDataFolder;
    private Label lblDataPath;
    private CheckBox chkAutoBackup;
    private Label lblBackupInterval;
    private NumericUpDown nudBackupInterval;
    private Label lblBackupMinutes;
    private Label lblBackupCopies;
    private NumericUpDown nudBackupCopies;
    private Label lblBackupRetention;
    private NumericUpDown nudBackupRetention;
    private Label lblBackupDays;
    private Label lblBackupHint;
    private Button btnBackupNow;
    private Button btnOpenBackupFolder;
    private Panel pnlBottom;
    private FlowLayoutPanel flpBottomButtons;
    private Button btnCancel;
    private Button btnSave;

    protected override void Dispose(bool disposing)
    {
        if (disposing) components?.Dispose();
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new Container();
        lblHeader = new Label();
        lblHeaderHint = new Label();
        tabSettings = new TabControl();
        tabGeneral = new TabPage();
        tabMonitoring = new TabPage();
        tabNotifications = new TabPage();
        tabJournal = new TabPage();
        tabBackups = new TabPage();
        chkStartMonitoring = new CheckBox();
        chkMinimizeToTray = new CheckBox();
        chkStartWithWindows = new CheckBox();
        chkAlwaysOnTop = new CheckBox();
        lblGeneralHint = new Label();
        lblInterval = new Label();
        nudInterval = new NumericUpDown();
        lblSeconds = new Label();
        lblTimeout = new Label();
        nudTimeout = new NumericUpDown();
        lblMilliseconds = new Label();
        lblFailures = new Label();
        nudFailures = new NumericUpDown();
        lblFailuresHint = new Label();
        lblSuccesses = new Label();
        nudSuccesses = new NumericUpDown();
        lblSuccessesHint = new Label();
        chkLatencyWarning = new CheckBox();
        lblLatencyThreshold = new Label();
        nudLatencyThreshold = new NumericUpDown();
        lblLatencyMs = new Label();
        lblLatencyChecks = new Label();
        nudLatencyChecks = new NumericUpDown();
        lblLatencyChecksUnit = new Label();
        lblLatencyHint = new Label();
        chkSoundOffline = new CheckBox();
        chkSoundOnline = new CheckBox();
        chkTrayNotifications = new CheckBox();
        btnTestOfflineSound = new Button();
        btnTestOnlineSound = new Button();
        lblRetention = new Label();
        nudRetention = new NumericUpDown();
        lblDays = new Label();
        chkAutoDelete = new CheckBox();
        btnOpenDataFolder = new Button();
        lblDataPath = new Label();
        chkAutoBackup = new CheckBox();
        lblBackupInterval = new Label();
        nudBackupInterval = new NumericUpDown();
        lblBackupMinutes = new Label();
        lblBackupCopies = new Label();
        nudBackupCopies = new NumericUpDown();
        lblBackupRetention = new Label();
        nudBackupRetention = new NumericUpDown();
        lblBackupDays = new Label();
        lblBackupHint = new Label();
        btnBackupNow = new Button();
        btnOpenBackupFolder = new Button();
        pnlBottom = new Panel();
        flpBottomButtons = new FlowLayoutPanel();
        btnCancel = new Button();
        btnSave = new Button();

        tabSettings.SuspendLayout();
        tabGeneral.SuspendLayout();
        tabMonitoring.SuspendLayout();
        tabNotifications.SuspendLayout();
        tabJournal.SuspendLayout();
        tabBackups.SuspendLayout();
        ((ISupportInitialize)nudInterval).BeginInit();
        ((ISupportInitialize)nudTimeout).BeginInit();
        ((ISupportInitialize)nudFailures).BeginInit();
        ((ISupportInitialize)nudSuccesses).BeginInit();
        ((ISupportInitialize)nudLatencyThreshold).BeginInit();
        ((ISupportInitialize)nudLatencyChecks).BeginInit();
        ((ISupportInitialize)nudRetention).BeginInit();
        ((ISupportInitialize)nudBackupInterval).BeginInit();
        ((ISupportInitialize)nudBackupCopies).BeginInit();
        ((ISupportInitialize)nudBackupRetention).BeginInit();
        pnlBottom.SuspendLayout();
        flpBottomButtons.SuspendLayout();
        SuspendLayout();

        lblHeader.AutoSize = true;
        lblHeader.Font = new Font("Segoe UI Semibold", 11.5F);
        lblHeader.Location = new Point(14, 10);
        lblHeader.Text = "Настройки";
        lblHeaderHint.AutoSize = true;
        lblHeaderHint.Font = new Font("Segoe UI", 7.25F);
        lblHeaderHint.Location = new Point(15, 34);
        lblHeaderHint.Text = "Параметры мониторинга и поведения программы.";

        tabSettings.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        tabSettings.Controls.Add(tabGeneral);
        tabSettings.Controls.Add(tabMonitoring);
        tabSettings.Controls.Add(tabNotifications);
        tabSettings.Controls.Add(tabJournal);
        tabSettings.Controls.Add(tabBackups);
        tabSettings.Location = new Point(14, 55);
        tabSettings.Name = "tabSettings";
        tabSettings.Size = new Size(392, 274);

        // Общие
        tabGeneral.BackColor = Color.White;
        tabGeneral.Controls.Add(chkStartMonitoring);
        tabGeneral.Controls.Add(chkMinimizeToTray);
        tabGeneral.Controls.Add(chkStartWithWindows);
        tabGeneral.Controls.Add(chkAlwaysOnTop);
        tabGeneral.Controls.Add(lblGeneralHint);
        tabGeneral.Text = "Общие";
        chkStartMonitoring.AutoSize = true;
        chkStartMonitoring.Location = new Point(14, 18);
        chkStartMonitoring.Text = "Запускать мониторинг при старте";
        chkMinimizeToTray.AutoSize = true;
        chkMinimizeToTray.Location = new Point(14, 48);
        chkMinimizeToTray.Text = "Сворачивать / закрывать окно в трей";
        chkStartWithWindows.AutoSize = true;
        chkStartWithWindows.Location = new Point(14, 78);
        chkStartWithWindows.Text = "Запускать вместе с Windows";
        chkAlwaysOnTop.AutoSize = true;
        chkAlwaysOnTop.Location = new Point(14, 108);
        chkAlwaysOnTop.Text = "Всегда поверх других окон";
        lblGeneralHint.Location = new Point(14, 146);
        lblGeneralHint.Size = new Size(345, 44);
        lblGeneralHint.Text = "При работе в трее мониторинг продолжает работать.\r\nПолный выход — через меню значка в трее.";

        // Мониторинг
        tabMonitoring.BackColor = Color.White;
        tabMonitoring.Controls.Add(lblInterval);
        tabMonitoring.Controls.Add(nudInterval);
        tabMonitoring.Controls.Add(lblSeconds);
        tabMonitoring.Controls.Add(lblTimeout);
        tabMonitoring.Controls.Add(nudTimeout);
        tabMonitoring.Controls.Add(lblMilliseconds);
        tabMonitoring.Controls.Add(lblFailures);
        tabMonitoring.Controls.Add(nudFailures);
        tabMonitoring.Controls.Add(lblFailuresHint);
        tabMonitoring.Controls.Add(lblSuccesses);
        tabMonitoring.Controls.Add(nudSuccesses);
        tabMonitoring.Controls.Add(lblSuccessesHint);
        tabMonitoring.Controls.Add(chkLatencyWarning);
        tabMonitoring.Controls.Add(lblLatencyThreshold);
        tabMonitoring.Controls.Add(nudLatencyThreshold);
        tabMonitoring.Controls.Add(lblLatencyMs);
        tabMonitoring.Controls.Add(lblLatencyChecks);
        tabMonitoring.Controls.Add(nudLatencyChecks);
        tabMonitoring.Controls.Add(lblLatencyChecksUnit);
        tabMonitoring.Controls.Add(lblLatencyHint);
        tabMonitoring.Text = "Мониторинг";
        lblInterval.AutoSize = true;
        lblInterval.Location = new Point(14, 18);
        lblInterval.Text = "Интервал:";
        nudInterval.Location = new Point(125, 14);
        nudInterval.Minimum = 1;
        nudInterval.Maximum = 3600;
        nudInterval.Value = 5;
        nudInterval.Size = new Size(65, 23);
        lblSeconds.AutoSize = true;
        lblSeconds.Location = new Point(196, 18);
        lblSeconds.Text = "сек.";
        lblTimeout.AutoSize = true;
        lblTimeout.Location = new Point(14, 50);
        lblTimeout.Text = "Timeout:";
        nudTimeout.Location = new Point(125, 46);
        nudTimeout.Minimum = 100;
        nudTimeout.Maximum = 30000;
        nudTimeout.Increment = 100;
        nudTimeout.Value = 1000;
        nudTimeout.Size = new Size(72, 23);
        lblMilliseconds.AutoSize = true;
        lblMilliseconds.Location = new Point(203, 50);
        lblMilliseconds.Text = "мс";
        lblFailures.AutoSize = true;
        lblFailures.Location = new Point(14, 82);
        lblFailures.Text = "Offline после:";
        nudFailures.Location = new Point(125, 78);
        nudFailures.Minimum = 1;
        nudFailures.Maximum = 20;
        nudFailures.Value = 3;
        nudFailures.Size = new Size(55, 23);
        lblFailuresHint.AutoSize = true;
        lblFailuresHint.Location = new Point(187, 82);
        lblFailuresHint.Text = "неудач подряд";
        lblSuccesses.AutoSize = true;
        lblSuccesses.Location = new Point(14, 114);
        lblSuccesses.Text = "Online после:";
        nudSuccesses.Location = new Point(125, 110);
        nudSuccesses.Minimum = 1;
        nudSuccesses.Maximum = 20;
        nudSuccesses.Value = 2;
        nudSuccesses.Size = new Size(55, 23);
        lblSuccessesHint.AutoSize = true;
        lblSuccessesHint.Location = new Point(187, 114);
        lblSuccessesHint.Text = "успехов подряд";
        chkLatencyWarning.AutoSize = true;
        chkLatencyWarning.Checked = true;
        chkLatencyWarning.Location = new Point(14, 150);
        chkLatencyWarning.Text = "Warning при высокой задержке";
        chkLatencyWarning.CheckedChanged += chkLatencyWarning_CheckedChanged;
        lblLatencyThreshold.AutoSize = true;
        lblLatencyThreshold.Location = new Point(14, 182);
        lblLatencyThreshold.Text = "Порог:";
        nudLatencyThreshold.Location = new Point(68, 178);
        nudLatencyThreshold.Minimum = 1;
        nudLatencyThreshold.Maximum = 30000;
        nudLatencyThreshold.Value = 100;
        nudLatencyThreshold.Size = new Size(68, 23);
        lblLatencyMs.AutoSize = true;
        lblLatencyMs.Location = new Point(142, 182);
        lblLatencyMs.Text = "мс";
        lblLatencyChecks.AutoSize = true;
        lblLatencyChecks.Location = new Point(181, 182);
        lblLatencyChecks.Text = "после";
        nudLatencyChecks.Location = new Point(224, 178);
        nudLatencyChecks.Minimum = 1;
        nudLatencyChecks.Maximum = 20;
        nudLatencyChecks.Value = 2;
        nudLatencyChecks.Size = new Size(48, 23);
        lblLatencyChecksUnit.AutoSize = true;
        lblLatencyChecksUnit.Location = new Point(278, 182);
        lblLatencyChecksUnit.Text = "проверок";
        lblLatencyHint.Location = new Point(14, 210);
        lblLatencyHint.Size = new Size(345, 34);
        lblLatencyHint.Text = "Высокий ping даёт жёлтый Warning, но не считается Offline\r\nи не создаёт лишних записей в журнале.";

        // Уведомления
        tabNotifications.BackColor = Color.White;
        tabNotifications.Controls.Add(chkSoundOffline);
        tabNotifications.Controls.Add(chkSoundOnline);
        tabNotifications.Controls.Add(chkTrayNotifications);
        tabNotifications.Controls.Add(btnTestOfflineSound);
        tabNotifications.Controls.Add(btnTestOnlineSound);
        tabNotifications.Text = "Уведомления";
        chkSoundOffline.AutoSize = true;
        chkSoundOffline.Location = new Point(14, 22);
        chkSoundOffline.Text = "Звук при Offline";
        btnTestOfflineSound.Location = new Point(278, 17);
        btnTestOfflineSound.Size = new Size(78, 27);
        btnTestOfflineSound.Text = "Проверить";
        btnTestOfflineSound.Click += btnTestOfflineSound_Click;
        chkSoundOnline.AutoSize = true;
        chkSoundOnline.Location = new Point(14, 58);
        chkSoundOnline.Text = "Звук при восстановлении";
        btnTestOnlineSound.Location = new Point(278, 53);
        btnTestOnlineSound.Size = new Size(78, 27);
        btnTestOnlineSound.Text = "Проверить";
        btnTestOnlineSound.Click += btnTestOnlineSound_Click;
        chkTrayNotifications.AutoSize = true;
        chkTrayNotifications.Location = new Point(14, 96);
        chkTrayNotifications.Text = "Показывать уведомления из трея";

        // Журнал
        tabJournal.BackColor = Color.White;
        tabJournal.Controls.Add(lblRetention);
        tabJournal.Controls.Add(nudRetention);
        tabJournal.Controls.Add(lblDays);
        tabJournal.Controls.Add(chkAutoDelete);
        tabJournal.Controls.Add(btnOpenDataFolder);
        tabJournal.Controls.Add(lblDataPath);
        tabJournal.Text = "Журнал";
        lblRetention.AutoSize = true;
        lblRetention.Location = new Point(14, 22);
        lblRetention.Text = "Хранить события:";
        nudRetention.Location = new Point(128, 18);
        nudRetention.Minimum = 1;
        nudRetention.Maximum = 3650;
        nudRetention.Value = 30;
        nudRetention.Size = new Size(65, 23);
        lblDays.AutoSize = true;
        lblDays.Location = new Point(199, 22);
        lblDays.Text = "дней";
        chkAutoDelete.AutoSize = true;
        chkAutoDelete.Location = new Point(14, 58);
        chkAutoDelete.Text = "Удалять старые события автоматически";
        btnOpenDataFolder.Location = new Point(14, 94);
        btnOpenDataFolder.Size = new Size(136, 27);
        btnOpenDataFolder.Text = "Открыть папку данных";
        btnOpenDataFolder.Click += btnOpenDataFolder_Click;
        lblDataPath.Location = new Point(14, 132);
        lblDataPath.Size = new Size(345, 56);

        // Резервные копии
        tabBackups.BackColor = Color.White;
        tabBackups.Controls.Add(chkAutoBackup);
        tabBackups.Controls.Add(lblBackupInterval);
        tabBackups.Controls.Add(nudBackupInterval);
        tabBackups.Controls.Add(lblBackupMinutes);
        tabBackups.Controls.Add(lblBackupCopies);
        tabBackups.Controls.Add(nudBackupCopies);
        tabBackups.Controls.Add(lblBackupRetention);
        tabBackups.Controls.Add(nudBackupRetention);
        tabBackups.Controls.Add(lblBackupDays);
        tabBackups.Controls.Add(lblBackupHint);
        tabBackups.Controls.Add(btnBackupNow);
        tabBackups.Controls.Add(btnOpenBackupFolder);
        tabBackups.Text = "Резерв";
        chkAutoBackup.AutoSize = true;
        chkAutoBackup.Checked = true;
        chkAutoBackup.Location = new Point(14, 18);
        chkAutoBackup.Text = "Автоматические резервные копии";
        chkAutoBackup.CheckedChanged += chkAutoBackup_CheckedChanged;
        lblBackupInterval.AutoSize = true;
        lblBackupInterval.Location = new Point(14, 54);
        lblBackupInterval.Text = "Не чаще чем:";
        nudBackupInterval.Location = new Point(111, 50);
        nudBackupInterval.Minimum = 1;
        nudBackupInterval.Maximum = 10080;
        nudBackupInterval.Value = 15;
        nudBackupInterval.Size = new Size(65, 23);
        lblBackupMinutes.AutoSize = true;
        lblBackupMinutes.Location = new Point(182, 54);
        lblBackupMinutes.Text = "мин.";
        lblBackupCopies.AutoSize = true;
        lblBackupCopies.Location = new Point(14, 86);
        lblBackupCopies.Text = "Макс. копий:";
        nudBackupCopies.Location = new Point(111, 82);
        nudBackupCopies.Minimum = 1;
        nudBackupCopies.Maximum = 999;
        nudBackupCopies.Value = 20;
        nudBackupCopies.Size = new Size(65, 23);
        lblBackupRetention.AutoSize = true;
        lblBackupRetention.Location = new Point(14, 118);
        lblBackupRetention.Text = "Удалять старше:";
        nudBackupRetention.Location = new Point(111, 114);
        nudBackupRetention.Minimum = 1;
        nudBackupRetention.Maximum = 3650;
        nudBackupRetention.Value = 30;
        nudBackupRetention.Size = new Size(65, 23);
        lblBackupDays.AutoSize = true;
        lblBackupDays.Location = new Point(182, 118);
        lblBackupDays.Text = "дней";
        lblBackupHint.Location = new Point(14, 150);
        lblBackupHint.Size = new Size(345, 42);
        lblBackupHint.Text = "Копия создаётся перед изменением конфигурации.\r\nСохраняются hosts.json и settings.json; журнал не дублируется.";
        btnBackupNow.Location = new Point(14, 202);
        btnBackupNow.Size = new Size(134, 27);
        btnBackupNow.Text = "Создать сейчас";
        btnBackupNow.Click += btnBackupNow_Click;
        btnOpenBackupFolder.Location = new Point(156, 202);
        btnOpenBackupFolder.Size = new Size(164, 27);
        btnOpenBackupFolder.Text = "Открыть папку копий";
        btnOpenBackupFolder.Click += btnOpenBackupFolder_Click;

        // Нижняя панель
        pnlBottom.BackColor = Color.White;
        pnlBottom.Controls.Add(flpBottomButtons);
        pnlBottom.Dock = DockStyle.Bottom;
        pnlBottom.Height = 44;
        flpBottomButtons.AutoSize = true;
        flpBottomButtons.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        flpBottomButtons.Controls.Add(btnSave);
        flpBottomButtons.Controls.Add(btnCancel);
        flpBottomButtons.Dock = DockStyle.Right;
        flpBottomButtons.FlowDirection = FlowDirection.RightToLeft;
        flpBottomButtons.Padding = new Padding(0, 8, 10, 0);
        flpBottomButtons.WrapContents = false;
        btnSave.Margin = new Padding(0, 0, 6, 0);
        btnSave.Size = new Size(78, 27);
        btnSave.Text = "Сохранить";
        btnSave.Click += btnSave_Click;
        btnCancel.DialogResult = DialogResult.Cancel;
        btnCancel.Margin = new Padding(0);
        btnCancel.Size = new Size(70, 27);
        btnCancel.Text = "Отмена";

        AcceptButton = btnSave;
        CancelButton = btnCancel;
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        ClientSize = new Size(420, 382);
        Controls.Add(lblHeader);
        Controls.Add(lblHeaderHint);
        Controls.Add(tabSettings);
        Controls.Add(pnlBottom);
        FormBorderStyle = FormBorderStyle.FixedDialog;
        MaximizeBox = false;
        MinimizeBox = false;
        Name = "SettingsForm";
        ShowInTaskbar = false;
        StartPosition = FormStartPosition.CenterParent;
        Text = "Настройки — IP Monitor";

        tabSettings.ResumeLayout(false);
        tabGeneral.ResumeLayout(false);
        tabGeneral.PerformLayout();
        tabMonitoring.ResumeLayout(false);
        tabMonitoring.PerformLayout();
        tabNotifications.ResumeLayout(false);
        tabNotifications.PerformLayout();
        tabJournal.ResumeLayout(false);
        tabJournal.PerformLayout();
        tabBackups.ResumeLayout(false);
        tabBackups.PerformLayout();
        ((ISupportInitialize)nudInterval).EndInit();
        ((ISupportInitialize)nudTimeout).EndInit();
        ((ISupportInitialize)nudFailures).EndInit();
        ((ISupportInitialize)nudSuccesses).EndInit();
        ((ISupportInitialize)nudLatencyThreshold).EndInit();
        ((ISupportInitialize)nudLatencyChecks).EndInit();
        ((ISupportInitialize)nudRetention).EndInit();
        ((ISupportInitialize)nudBackupInterval).EndInit();
        ((ISupportInitialize)nudBackupCopies).EndInit();
        ((ISupportInitialize)nudBackupRetention).EndInit();
        pnlBottom.ResumeLayout(false);
        pnlBottom.PerformLayout();
        flpBottomButtons.ResumeLayout(false);
        flpBottomButtons.PerformLayout();
        ResumeLayout(false);
        PerformLayout();
    }
}
